export type SkillSuggestion = {
  id: string;
  label: string;
};

const SKILL_LABELS = [
  'Accounting',
  'Accounts payable',
  'Accounts receivable',
  'Active listening',
  'Administrative support',
  'Adobe Acrobat',
  'Adobe Creative Cloud',
  'Agile methodology',
  'Amazon Web Services',
  'Analytical thinking',
  'Applicant tracking systems',
  'Appointment scheduling',
  'ASP.NET Core',
  'Auditing',
  'AutoCAD',
  'Budgeting',
  'Business analysis',
  'Business development',
  'Business intelligence',
  'C#',
  'Cash flow',
  'Change management',
  'Client relations',
  'Cloud computing',
  'Coaching',
  'Cold calling',
  'Commercial lending',
  'Communication',
  'Compliance',
  'Conflict resolution',
  'Construction management',
  'Continuous improvement',
  'Contract negotiation',
  'Copywriting',
  'Cost analysis',
  'Credit analysis',
  'CRM software',
  'CSS',
  'Customer service',
  'Data analysis',
  'Data entry',
  'Data visualization',
  'Database management',
  'Decision making',
  'Digital marketing',
  'Document management',
  'Editing',
  'Employee relations',
  'Event planning',
  'Excel',
  'Expense reporting',
  'Financial analysis',
  'Financial modeling',
  'Financial reporting',
  'Financial statements',
  'Forecasting',
  'Forklift operation',
  'Front desk operations',
  'Git',
  'Google Analytics',
  'Google Workspace',
  'Graphic design',
  'HTML',
  'Human resources',
  'Inventory management',
  'Invoice processing',
  'Java',
  'JavaScript',
  'Jira',
  'KPI reporting',
  'Leadership',
  'Lean manufacturing',
  'Loan origination',
  'Loans',
  'Logistics',
  'Management',
  'Market research',
  'Marketing strategy',
  'Microsoft Access',
  'Microsoft Azure',
  'Microsoft Dynamics',
  'Microsoft Excel',
  'Microsoft Office',
  'Microsoft Outlook',
  'Microsoft Power BI',
  'Microsoft PowerPoint',
  'Microsoft Project',
  'Microsoft Teams',
  'Microsoft Word',
  'Negotiation',
  'Node.js',
  'Operations management',
  'Payroll',
  'Performance management',
  'Phone etiquette',
  'Policy development',
  'Power BI',
  'Presentation skills',
  'Problem solving',
  'Process improvement',
  'Procurement',
  'Product management',
  'Project coordination',
  'Project management',
  'Public speaking',
  'Python',
  'Quality assurance',
  'QuickBooks',
  'React',
  'Real estate lending',
  'Reconciliation',
  'Recruiting',
  'Relationship management',
  'Reporting',
  'Research',
  'REST APIs',
  'Retail sales',
  'Risk analysis',
  'Sales',
  'Salesforce',
  'Scheduling',
  'Search engine optimization',
  'SharePoint',
  'Six Sigma',
  'Social media management',
  'SQL',
  'Staff training',
  'Strategic planning',
  'Supply chain management',
  'Tableau',
  'Tax preparation',
  'Team building',
  'Technical support',
  'Time management',
  'Training and development',
  'Troubleshooting',
  'TypeScript',
  'Underwriting',
  'Vendor management',
  'Visual Basic for Applications',
  'Wireframes',
  'Writing'
];

export const SKILL_SUGGESTIONS: SkillSuggestion[] = SKILL_LABELS.map((label) => ({
  id: label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  label
}));
