import { KeyRound, ShieldCheck, Cloud, FileText } from 'lucide-react';

const settingsSections = [
  {
    title: 'AI Provider',
    status: 'Backend managed',
    icon: KeyRound,
    copy: 'Provider credentials belong to backend configuration and encrypted account settings, not resume-editing screens.'
  },
  {
    title: 'Document Export',
    status: 'PDF first',
    icon: FileText,
    copy: 'PDF and DOCX exports are generated by backend services from structured resume data.'
  },
  {
    title: 'Storage',
    status: 'Not connected',
    icon: Cloud,
    copy: 'Google Drive and OneDrive storage adapters are optional destinations for generated artifacts.'
  },
  {
    title: 'Security',
    status: 'Required',
    icon: ShieldCheck,
    copy: 'Sensitive provider, OAuth, and packet data stay out of the browser workflow wherever possible.'
  }
];

export default function Settings() {
  return (
    <div className="page-stack">
      <header className="page-header">
        <div>
          <h2 className="page-title">Settings</h2>
          <p className="page-copy">Control provider, export, storage, and security boundaries.</p>
        </div>
      </header>

      <section className="responsive-grid" aria-label="Application settings">
        {settingsSections.map((section) => {
          const Icon = section.icon;

          return (
            <article className="surface-panel page-stack" style={{ padding: '24px' }} key={section.title}>
              <div className="toolbar-row">
                <Icon size={24} aria-hidden="true" />
                <span className="status-pill">{section.status}</span>
              </div>
              <div>
                <h3 className="section-title">{section.title}</h3>
                <p className="section-copy">{section.copy}</p>
              </div>
            </article>
          );
        })}
      </section>
    </div>
  );
}
