import { CalendarDays, KeyRound, ShieldCheck, Cloud, FileText } from 'lucide-react';
import AppSelect from '../components/ui/AppSelect';
import { useDateFormatPreference } from '../features/preferences/dateFormatPreference';
import type { DateFormatPreference } from '../features/preferences/dateFormatPreference';

type DateFormatOption = {
  label: string;
  value: DateFormatPreference;
};

const DATE_FORMAT_OPTIONS: DateFormatOption[] = [
  { label: 'Month/day/year (MM/DD/YYYY)', value: 'MM/DD/YYYY' },
  { label: 'Day/month/year (DD/MM/YYYY)', value: 'DD/MM/YYYY' }
];

const settingsSections = [
  {
    title: 'AI Provider',
    status: 'Backend managed',
    icon: KeyRound,
    copy: 'Provider credentials belong to backend configuration and encrypted account settings, not resume-editing screens.'
  },
  {
    title: 'Document Export',
    status: 'PDF first',
    icon: FileText,
    copy: 'PDF and DOCX exports are generated by backend services from structured resume data.'
  },
  {
    title: 'Storage',
    status: 'Not connected',
    icon: Cloud,
    copy: 'Google Drive and OneDrive storage adapters are optional destinations for generated artifacts.'
  },
  {
    title: 'Security',
    status: 'Required',
    icon: ShieldCheck,
    copy: 'Sensitive provider, OAuth, and packet data stay out of the browser workflow wherever possible.'
  }
];

export default function Settings() {
  const { dateFormat, setDateFormat } = useDateFormatPreference();

  return (
    <div className="page-stack">
      <header className="page-header">
        <div>
          <h2 className="page-title">Settings</h2>
          <p className="page-copy">Control regional preferences, providers, exports, storage, and security boundaries.</p>
        </div>
      </header>

      <section className="surface-panel settings-preferences-panel" aria-labelledby="regional-preferences-title">
        <div className="settings-preferences-heading">
          <CalendarDays aria-hidden="true" size={24} />
          <div>
            <h3 className="section-title" id="regional-preferences-title">Regional Preferences</h3>
            <p className="section-copy">Control how dates are entered and displayed throughout ApplyFill.</p>
          </div>
        </div>
        <div className="form-group settings-date-format-field">
          <label className="form-label" htmlFor="date-format-preference">Date Format</label>
          <AppSelect<DateFormatOption>
            inputId="date-format-preference"
            isSearchable={false}
            onChange={(option) => {
              if (option) setDateFormat(option.value);
            }}
            options={DATE_FORMAT_OPTIONS}
            value={DATE_FORMAT_OPTIONS.find((option) => option.value === dateFormat)}
          />
        </div>
      </section>

      <section className="responsive-grid" aria-label="Application settings">
        {settingsSections.map((section) => {
          const Icon = section.icon;

          return (
            <article className="surface-panel page-stack" style={{ padding: '24px' }} key={section.title}>
              <div className="toolbar-row">
                <Icon size={24} aria-hidden="true" />
                <span className="status-pill">{section.status}</span>
              </div>
              <div>
                <h3 className="section-title">{section.title}</h3>
                <p className="section-copy">{section.copy}</p>
              </div>
            </article>
          );
        })}
      </section>
    </div>
  );
}
